#Requires -Version 5
# https://github.com/haiwen/seafile/issues/288

# Modify this if the script isn't in the root of a Seafile library
$rootPath = $PSScriptRoot

# Extension to use for symlink placeholders
$symExt = 'seaflnk'

# This is the separator b/w your ignored files, and auto-ignored symlinks
$ignoreNeedle = '### SEAFILE-SYMLINK (AUTOGENERATED) ###'
$ignoreWarning = '# Do not modify the line above or anything below it'


# Helper function for retrieving one path relative to another
function Get-RelativePath ([string]$PathFrom, [string]$PathTo) {
    Push-Location -Path $PathFrom
    $out = Resolve-Path -Relative $PathTo
    Pop-Location
    $out
}


# Returns System.IO.FileSystemInfo of seafile-ignore.txt, creating it if necessary
function Get-SeafileIgnoreFile {
    if (Test-Path "$rootPath\seafile-ignore.txt") {
        Write-Host "Found $rootPath\seafile-ignore.txt"
        Get-Item -Path "$rootPath\seafile-ignore.txt"
    } else {
        Write-Host "Created $rootPath\seafile-ignore.txt"
        New-Item -Path $rootPath -Name "seafile-ignore.txt" -Type "file"
    }
}


# Convert an array into a hastable, with every two array members forming a name-value pair.
# https://stackoverflow.com/questions/27764394/get-valuefromremainingarguments-as-an-hashtable
function Get-ParamHash {
    param (
        [string[]]
        $ParamArray
    )
    process {
        $ParamHash = @{}
        for ($i = 0; $i -lt $ParamArray.count; $i+=2) {
            $ParamHash[($ParamArray[$i] -replace '^-+' -replace ':$')] = $ParamArray[$i+1]
        }
        $ParamHash
    }
}


# Helper to find files recursively within a given directory.
# Accepts the same named params as `Get-ChildItem`... except maybe `Path`?
# The cucial difference vs. `Get-ChildItem` is that this doesn't follow symlinks.
# First positional param is the path to the directory within which to search.
function Get-SymbolicPaths {
    param (
        [string]
        $DirPath,

        [parameter(ValueFromRemainingArguments=$true)]
        [string[]]
        $ParamArray
    )
    process {
        # Convert param list to hash
        $params = Get-ParamHash $ParamArray

        # Get symbolic links located directly within this directory
        $links = @(Get-ChildItem -Path "$DirPath\*" @params | ForEach-Object { $_.FullName })

        # Get all subdirectories, excluding symbolic links
        $subdirs = @(Get-ChildItem -Path $DirPath -Attributes Directory+!ReparsePoint)

        # Call this function on each subdirectory and append the result
        foreach ($subdir in $subdirs) {
            $links += Get-SymbolicPaths $subdir.FullName @params
        }

        @($links | Where-Object { $_ })  # Remove empty items
    }
}


# This should detect SymbolicLinks, but not HardLinks or Junctures (intentionally)
# https://stackoverflow.com/questions/817794/find-out-whether-a-file-is-a-symbolic-link-in-powershell
function Get-SymbolicLinks ([string]$DirPath) {
    Get-SymbolicPaths $DirPath -Attributes ReparsePoint
}


# Find placeholder files recursively, returning their paths.
Function Get-SymbolicPlaceholders ([string]$DirPath) {
    Get-SymbolicPaths $DirPath -Include "*.$symExt"
}


# Split the ignore file into two parts based on our needle
$siContent = Get-Content (Get-SeafileIgnoreFile)
$siPrefix = $siContent.Where({ $_ -Like $ignoreNeedle }, 'Until')

# Create the suffix header
$siSuffix = @($ignoreNeedle, $ignoreWarning)

# Ensure that a newline precedes the suffix
if (![string]::IsNullOrEmpty($siPrefix[-1])) {
    $siPrefix += ''
}

# For comparison's sake, do the same to the source
if (![string]::IsNullOrEmpty($siContent[-1])) {
    $siContent += ''
}

# Look for symlink placeholder files, and create symlinks from them
$phPaths = Get-SymbolicPlaceholders $rootPath

foreach ($phPath in $phPaths) {

    $placeholder = Get-Item -Path $phPath

    # Assumes file w/ single line, no empty trailing ones
    $destPath = Get-Content $placeholder
    $linkPath = $phPath.TrimEnd($symExt)

    # We need to enter the folder where the symlink will be located for relative paths to resolve
    Push-Location -Path (Split-Path $linkPath -Parent)

    # https://stackoverflow.com/questions/894430/creating-hard-and-soft-links-using-powershell
    $link = New-Item -Path $linkPath -ItemType SymbolicLink -Value $destPath -Force

    # Restore our working directory
    Pop-Location

    Write-Host "Created symlink: `"$linkPath`" >>> `"$destPath`""

}

$linkPaths = Get-SymbolicLinks $rootPath

foreach ($linkPath in $linkPaths) {

    $link = Get-Item -Path $linkPath

    # Let's work with absolute paths for ease of comparison
    $linkPathAbs = $link.FullName
    $destPathAbs = $link | Select-Object -ExpandProperty Target

    # Get the directory in which the symlink is located
    $linkParentPathAbs = Split-Path $linkPathAbs -Parent

    # Normalize the target path if it's actually relative
    # https://stackoverflow.com/questions/495618/how-to-normalize-a-path-in-powershell
    if (![System.IO.Path]::IsPathRooted($destPathAbs)) {
        $destPathAbs = Join-Path ($linkParentPathAbs) $destPathAbs
        $destPathAbs = [System.IO.Path]::GetFullPath($destPathAbs)
    }

    # Check if the link refers to a directory or a file
    $destIsDir = (Get-Item -Path $destPathAbs) -is [System.IO.DirectoryInfo]

    # Determine the relative path from library root to the symlink for ignoring
    $linkIgnorePath = Get-RelativePath $rootPath $linkPathAbs
    $linkIgnorePath = $linkIgnorePath.TrimStart('.\')
    $linkIgnorePath = $linkIgnorePath.Replace('\','/')

    # TODO: Test if symbolic links to folders require forwardslash or absence thereof
    # https://www.seafile.com/en/help/ignore/
    if ($destIsDir) {
        $linkIgnorePath = $linkIgnorePath + '/'
    }

    $siSuffix += $linkIgnorePath

    # If the path falls below the library root, keep it absolute, else make it relative
    if (!$destPathAbs.StartsWith($rootPath)) {
        $destPath = $destPathAbs
    } else {
        $destPath = Get-RelativePath $linkParentPathAbs $destPathAbs
    }

    # Create a symlink placeholder file
    $phName = $link.Name + '.' + $symExt
    $phFile = New-Item -Path $linkParentPathAbs -Name $phName -Type "file" -Value $destPath -Force

    Write-Host "Created placeholder: `"$phFile`" >>> `"$destPath`""

}

# Add suffix to prefix with trailing newline
$siContentNew = $siPrefix + $siSuffix + ''

# Check if seafile-ignore.txt was empty of if there were any changes
# https://stackoverflow.com/questions/9598173/comparing-array-variables-in-powershell
$hasChanged = !$siContent -or @(Compare-Object $siContent $siContentNew -SyncWindow 0).Length -gt 0

if ($hasChanged) {
    $output = $siContentNew -Join "`n"
    New-Item -Path "$rootPath" -Name "seafile-ignore.txt" -Type "file" -Value $output -Force | Out-Null
    Write-Host "Updated seafile-ignore.txt"
} else {
    Write-Host "No changes to seafile-ignore.txt required"
}
